image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip3 install -r requirements.txt
    command: |
      foundryup
      # build mock wallet
      yarn --cwd browser/mock_wallet build
      python3 app.py

ports:
  - name: StoryCheck Web App
    port: 7860
    onOpen: open-preview

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-python.python
    - ms-python.isort
    - charliermarsh.ruff
