image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pyenv versions
      pip3 install -r requirements.txt
    command: |
      foundryup
      pyenv versions
      # redo pip3 installs that are not preserved from init stage
      pip3 install -r requirements.txt
      python3 app.py

ports:
  - name: StoryCheck Web App
    port: 7860
    onOpen: open-preview

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - charliermarsh.rufftasks
    - ms-python.python
    - ms-python.isort
