
tasks:
  - init: |
      pip3 install -r requirements.txt
      playwright install
      playwright install-deps
      curl -L https://foundry.paradigm.xyz | bash
    command: |
      source /home/gitpod/.bashrc
      foundryup
      python3 app.py

ports:
  - name: StoryCheck Web App
    port: 7860
    onOpen: open-preview
