
tasks:
  - init: |
      pip3 install -r requirements.txt
      playwright install
      playwright install-deps
    command: python3 app.py

ports:
  - name: StoryCheck Web App
    port: 7860
    onOpen: open-preview
