image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # install python app dependencies
      pip3 install -r requirements.txt
      # build mock wallet
      cd interpreter/browser/mock_wallet
      yarn install --non-interactive
      yarn bundle
      cd -
    command: |
      foundryup
      ./run.sh

ports:
  - name: StoryCheck Web App
    port: 7860
    onOpen: open-preview

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - ms-python.python
    - ms-python.isort
    - charliermarsh.ruff
