name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install Python deps with uv
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install ruff pre-commit pytest -r requirements.txt
        # Temporarily skip mock wallet build to focus on pytest
        # cd interpreter/browser/mock_wallet
        # yarn install --non-interactive
        # yarn bundle
    - name: Run lint
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
        ruff check . --line-length=120 --extend-ignore=E203
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
