name: StoryCheck CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: '0.8.4'

    - name: Install Python deps with uv
      run: |
        uv pip install --system flake8 pytest -r requirements.txt
        # build mock wallet
        cd interpreter/browser/mock_wallet
        yarn install --non-interactive
        yarn bundle

    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=120 --extend-ignore=E203

    - name: Run tests
      run: |
        pytest