name: StoryCheck Simple Web3 App

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm dependencies
        run: pnpm install
        working-directory: examples/simple-web3-app
      - name: Start Vite server and verify
        run: |
          pnpm dev &
          sleep 5
          curl --retry 5 --retry-delay 2 --retry-max-time 30 http://localhost:5173
        working-directory: examples/simple-web3-app
      - name: Run StoryCheck
        uses: ./
        # uses: GuardianUI/storycheck@v0.1.2  # For third-party apps, replace with the latest stable tagged version
        with:
          storypath: 'examples/simple-web3-app'
          start-command: 'pnpm dev'
          wait-on: 'http://localhost:5173'
          wait-on-timeout: '60'
          app-working-directory: 'examples/simple-web3-app'
      - name: Check if passed
        if: ${{ steps.storycheck.outputs.passed != 'true' }}
        run: echo "StoryCheck failed!" && exit 1